test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,7 +32,15 @@ jobs:
       id: plan
       continue-on-error: true
       run: |
+        set -eu
         make plan 'ACCNAME=${{env.ACCNAME}}' 'ENVNAME=${{env.ENVNAME}}' 'REGION=${{env.AWS_REGION}}'
+        terraform_exitcode=$?
+        if [ $terraform_exitcode -eq 2 ]; then
+          echo "Terraform succeeded with updates"
+        else
+          echo "ERROR: terraform exited with code $terraform_exitcode"
+          exit 1
+        fi
     - name: Terraform Apply Status
       id: apply
       run: |
